# Generated by Django 3.2.5 on 2021-08-06 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('time', models.DateTimeField()),
                ('patientName', models.CharField(max_length=64)),
                ('patientId', models.IntegerField()),
                ('department', models.CharField(max_length=64)),
            ],
        ),
    ]
