# Generated by Django 3.2.5 on 2021-08-06 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0002_remove_appointment_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ID', to='appointments.patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patientName',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Name', to='appointments.patient'),
        ),
    ]
