# Generated by Django 5.1.6 on 2025-02-26 16:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("appointments", "0002_alter_appointment_id_alter_department_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="patient",
            name="phone",
            field=models.CharField(default="", max_length=20),
        ),
    ]
