# Generated by Django 3.2.5 on 2021-08-06 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0003_auto_20210806_1113'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appointment',
            old_name='patientName',
            new_name='patient',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='patientId',
        ),
    ]
