# Generated by Django 3.2.5 on 2021-08-14 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0005_auto_20210810_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='notes',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
