# Generated by Django 2.2.24 on 2021-08-21 06:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0008_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
