# Generated by Django 2.2.24 on 2021-08-27 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0010_patient_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(default=''),
        ),
    ]
