# Generated by Django 2.2.24 on 2021-08-27 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0011_auto_20210827_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(default=0),
        ),
    ]
