# Generated by Django 2.2.24 on 2021-08-27 16:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0017_auto_20210827_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='Male', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='0', max_length=64),
            preserve_default=False,
        ),
    ]
