# Generated by Django 2.2.24 on 2021-08-27 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0018_auto_20210827_2143'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
