# Generated by Django 2.2.24 on 2021-08-27 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0019_remove_patient_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
    ]
