# Generated by Django 2.2.24 on 2021-08-27 17:09

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0021_auto_20210827_2205'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
        migrations.AlterField(
            model_name='patient',
            name='gender',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.IntegerField(default=2),
        ),
    ]
