# Generated by Django 2.2.24 on 2021-08-27 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0022_auto_20210827_2209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='phone',
        ),
    ]
