# Generated by Django 2.2.24 on 2021-08-28 10:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0025_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='appointment',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='appointments.Appointment'),
            preserve_default=False,
        ),
    ]
