# Generated by Django 2.2.24 on 2021-08-28 10:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0026_department_appointment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='appointment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='appointments.Appointment'),
        ),
    ]
