# Generated by Django 2.2.24 on 2021-08-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointments', '0033_appointment_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='identification',
            field=models.CharField(default='', max_length=6),
            preserve_default=False,
        ),
    ]
